baseURL = 'https://leventyalcin.com/'
theme = 'hugo-theme-nix'
languageCode = 'en-gb'

[params]

    Name = "Levent Yalcin"
    HeaderUsername = "levops"
    HeaderHostname = "cloud"
    About = "Hello! I am Levent. Your usual Cloud Platform Engineer. I came here to drink milk and automate everything, and I've just finished my milk!"
    ProfilePicture = "https://en.gravatar.com/userimage/14633204/208e79879fcab7bbadf654c3f64de43c.png"

    keywords = "blog,sre,devops,devsecops,automation,personal" # Site keywords.

    # CvURL = "your_cv_url"
    # Email = "your_email"
    # FacebookID = "your_facebook"
    KeybaseID = "leventyalcin"
    GithubID = "leventyalcin"
    GitlabId = "leventyalcin"
    GnuPGFingerprint = "06c127ddd6565cdab3cfef4b26426b2d80c07fbe"
    # GoogleAnalytics = "your_google_analytics_id"
    # GoogleplusID = "your_googleplus"
    # InstagramID = "your_instagram"
    LinkedInID = "leventyalcin"
    # MastodonURL = "your_mastodon_profile"
    MediumID = "levops"
    # Mobile = ""
    # PayPalMeID = "https://www.paypal.me/..."
    # Phone = ""
    # RedditID = "your_reddit"
    # SlackURL = "https://join.slack.com/..."
    SpotifyID = "leventyalcin"
    # SoundcloudID = "your_soundcloud_id"
    # StackExchangeID = "your_stackexchange_id"
    # StackOverflowID = "your_stackoverflow_id"
    # TelegramID = "your_telegram"
    TwitterID = "leventyalcin"
    # For youtube, since there are multiple path urls please add everything after https://youtube.com/ in channel url
    # YoutubeID = "c/your_youtube_id"

[deployment]

[[deployment.targets]]
name = "prod"
URL = "s3://leventyalcin.com"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
